package firenze;

import capasdecontrol.FirenzeBean;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Charlie Corner
 * @author Yasmin Torres
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        this.bean = new FirenzeBean();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lista = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        butArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        LabelHecInic = new javax.swing.JLabel();
        LabelObj = new javax.swing.JLabel();
        ComboObjetivo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaHechosInicio = new javax.swing.JList();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        butDeduccion = new javax.swing.JButton();
        butInduccion = new javax.swing.JButton();
        butLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butArchivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        butArchivo.setText("Cargar Archivo de Reglas");
        butArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butArchivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ALGORITMOS DE INFERENCIA");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "El algoritmo obtuvo como resultado:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        resultTextArea.setColumns(20);
        resultTextArea.setEditable(false);
        resultTextArea.setRows(5);
        resultTextArea.setBorder(null);
        resultTextArea.setEnabled(bean.isActivarBoton());
        jScrollPane2.setViewportView(resultTextArea);

        jScrollPane2.setBounds(20, 30, 320, 260);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Requisitos:"));

        LabelHecInic.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LabelHecInic.setText("Hechos de Inicio:");
        LabelHecInic.setBounds(20, 30, 83, 14);
        jLayeredPane2.add(LabelHecInic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelObj.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LabelObj.setText("Objetivo:");
        LabelObj.setBounds(20, 130, 45, 14);
        jLayeredPane2.add(LabelObj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ComboObjetivo.setEnabled(bean.isActivarBoton());
        ComboObjetivo.setBounds(110, 130, 170, 27);
        jLayeredPane2.add(ComboObjetivo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        listaHechosInicio.setEnabled(bean.isActivarBoton());
        jScrollPane1.setViewportView(listaHechosInicio);

        jScrollPane1.setBounds(110, 20, 170, 90);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmos"));

        butDeduccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        butDeduccion.setText("Deduccion");
        butDeduccion.setEnabled(bean.isActivarBoton());
        butDeduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeduccionActionPerformed(evt);
            }
        });
        butDeduccion.setBounds(20, 30, 80, 30);
        jLayeredPane4.add(butDeduccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        butInduccion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        butInduccion.setText("Inducción");
        butInduccion.setEnabled(bean.isActivarBoton());
        butInduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInduccionActionPerformed(evt);
            }
        });
        butInduccion.setBounds(110, 30, 80, 27);
        jLayeredPane4.add(butInduccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        butLimpiar.setText("Limpiar");
        butLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(butArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(butLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                                .addGap(29, 29, 29)))
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDeduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeduccionActionPerformed
        resultTextArea.setText("");
        List<String> hechosDeInicio = new ArrayList<String>();
        
        for(Object o: Arrays.asList(this.listaHechosInicio.getSelectedValues())){
            hechosDeInicio.add(o.toString());
        }
        
        bean.setListaHechosDeInicioSeleccionados(hechosDeInicio);
        bean.correrAlgoritmoDeduccion();
        resultTextArea.setText(bean.getResultado());
    }//GEN-LAST:event_butDeduccionActionPerformed

    private void butArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            bean.setArchivoDeRegla(fc.getSelectedFile());
            System.out.println(fc.getSelectedFile().getAbsolutePath());
            this.ComboObjetivo.setModel(new DefaultComboBoxModel(bean.getComboDeObjetivosASeleccionar().toArray()));
            this.listaHechosInicio.setModel( new DefaultComboBoxModel(bean.getListaHechosDeInicioASeleccionar().toArray()));
            this.listaHechosInicio.setEnabled(bean.isActivarBoton());
            this.ComboObjetivo.setEnabled(bean.isActivarBoton());
            this.resultTextArea.setEnabled(bean.isActivarBoton());
            this.butDeduccion.setEnabled(bean.isActivarBoton());
            this.butInduccion.setEnabled(bean.isActivarBoton());
        }
    }//GEN-LAST:event_butArchivoActionPerformed

    private void butLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarActionPerformed
        File archivo = bean.getArchivoDeRegla();
        bean = new FirenzeBean();
        resultTextArea.setText("");
        listaHechosInicio.setSelectedIndices(new int[0]);
        ComboObjetivo.setSelectedIndex(0);
        
        if (null != archivo) {
            bean.setArchivoDeRegla(archivo);
        }
    }//GEN-LAST:event_butLimpiarActionPerformed

    private void butInduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInduccionActionPerformed
        List<String> hechosDeInicio = new ArrayList<String>();
        resultTextArea.setText("");
        
        for(Object o: Arrays.asList(this.listaHechosInicio.getSelectedValues())){
            hechosDeInicio.add(o.toString());
        }
        
        bean.setListaHechosDeInicioSeleccionados(hechosDeInicio);
        bean.setObjetivo(ComboObjetivo.getSelectedItem().toString());
        bean.correrAlgoritmoInduccion();
        resultTextArea.setText(bean.getResultado());
    }//GEN-LAST:event_butInduccionActionPerformed

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboObjetivo;
    private javax.swing.JLabel LabelHecInic;
    private javax.swing.JLabel LabelObj;
    private javax.swing.ButtonGroup Lista;
    private javax.swing.JButton butArchivo;
    private javax.swing.JButton butDeduccion;
    private javax.swing.JButton butInduccion;
    private javax.swing.JButton butLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaHechosInicio;
    private javax.swing.JTextArea resultTextArea;
    // End of variables declaration//GEN-END:variables
    private FirenzeBean bean;
}
